# Generated by Django 2.2.1 on 2019-06-25 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverGauge',
            fields=[
                ('dws_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('obsStart', models.CharField(max_length=17)),
                ('obsEnd', models.CharField(max_length=17)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
