# Generated by Django 2.2.1 on 2019-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaugedata', '0004_auto_20190716_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='area',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='arf',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='lc',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='s1085',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='tc',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
